# Get the base Ubuntu image from Docker Hub
FROM c-plus-plus-with-boost:latest
MAINTAINER Jason Hui <huilapman@gmail.com>

ARG BOOST_VERSION=1_69_0

#ENV http_proxy http://192.168.195.153:3128
#ENV https_proxy http://192.168.195.153:3128

WORKDIR /home

# Clone git repository with dummy C++ program, use make to compile, install it, then remove the repo
RUN cd /home \
  && export GIT_SSL_NO_VERIFY=1 \
  && git clone https://github.com/pblischak/boost-docker-test.git \
  && cd /home/boost-docker-test \
  && make linux \
  && make install \
  && cd .. \
  && rm -rf boost-docker-test

CMD ["bash"]
